export { default as Hero } from './Hero';
export { default as TechMarquee } from './TechMarquee';
export { default as TechStack } from './TechStack';
export { default as About } from './About';
export { default as Skills } from './Skills';
export { default as Services } from './Services';
export { default as Projects } from './Projects';
export { default as Experience } from './Experience';
export { default as Contact } from './Contact';
